### ISSUE TITLE
Support Gradle 8.2+

### ISSUE THREAD

**Issue by gmitch215** [MinecraftForge/ForgeGradle#933]
If you upgrade the Gradle Wrapper to 8.2 or above, upon building this error appears:

```
java.lang.NoSuchMethodError: 'void org.gradle.api.internal.artifacts.repositories.descriptor.FlatDirRepositoryDescriptor.<init>(java.lang.String, java.util.Collection)'
```

It builds properly on Gradle 8.1.x. I believe this has to do with breaking changes in Gradle 8.2.

Edit: I saw #929 and created a linked issue at MinecraftForge/Artifactural#9

**Comment by LexManos** [comment]
I can do another stopgap fix for this. But gradle is know to break a lot of things on a whim. So I'm currently rewriting the entire FG toolchain to not be as horrible as people have let it become. It's just a matter of development time. 

For now, it's on my todo for a stopgap fix. But a low priority.

**Comment by gmitch215** [comment]
> LexManos

Any updates on this? Sorry for reviving this issue, but Gradle's been updated to 8.5, and there are a couple of API additions that make life easier. Is there a potential ETA?

**Comment by PaintNinja** [comment]
It should work on 8.4 already and 8.5 isn't stable yet

**Comment by gmitch215** [comment]
> It should work on 8.4 already and 8.5 isn't stable yet

Gradle for 8.5 was released as stable about 11 hours ago. But thanks, I'll try it out when I get the chance.

**Comment by gmitch215** [comment]
> It should work on 8.4 already and 8.5 isn't stable yet

Still doesn't work:
```
> Failed to notify project evaluation listener.
   > 'void org.gradle.api.internal.artifacts.repositories.descriptor.FlatDirRepositoryDescriptor.<init>(java.lang.String, java.util.Collection)'
   > 'void org.gradle.api.internal.artifacts.repositories.descriptor.FlatDirRepositoryDescriptor.<init>(java.lang.String, java.util.Collection)'
   ```

**Comment by LexManos** [comment]
Should be solved with https://github.com/MinecraftForge/ForgeGradle/pull/936
