### ISSUE TITLE
Gradle 8.2 Error

### ISSUE THREAD

**Issue by cech12** [MinecraftForge/ForgeGradle#929]
Hey, 

after upgrading Gradle to 8.2 I get this error when I sync my Gradle script of my Minecraft mod:
```
Caused by: java.lang.NoSuchMethodError: 'void org.gradle.api.internal.artifacts.repositories.descriptor.FlatDirRepositoryDescriptor.<init>(java.lang.String, java.util.Collection)'
	at net.minecraftforge.artifactural.gradle.GradleRepositoryAdapter.getDescriptor(GradleRepositoryAdapter.java:232)
```

I hope you can help me and find the issue. :)

Full stacktrace: https://pastebin.com/393pH201

My gradle script: https://github.com/cech12/BucketLib/blob/1.20/build.gradle

**Comment by LexManos** [comment]
It seems that Gradle [changed some of their internals](https://github.com/gradle/gradle/commit/7a7c460b601299fa2f9c3afb2d73b37e2556de86) in 8.2. [Artifactural ](https://github.com/MinecraftForge/Artifactural/blob/master/src/gradlecomp/java/net/minecraftforge/artifactural/gradle/GradleRepositoryAdapter.java#L231) would need to be updated. Gunna tag Shrimp or anyone else on the gradle team if they wanna care about it.

**Comment by cech12** [comment]
Fixed in NeoGradle
